version: '3'

services:
  mysql_slimcv:
    image: mysql:latest
    restart: always
    ports:
      - 3013:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql_slimcv
      MYSQL_USER: 
      MYSQL_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - 8113:80
    environment:
      PMA_HOST: mysql_slimcv
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root

volumes:
  db_data:







# version: "3.8"

# services:
#   php:
#     container_name: slim_php
#     build:
#       context: ./docker/php
#     ports:
#       - '9000:9000'
#     volumes:
#       - .:/var/www/slim_app

#   nginx:
#     container_name: slim_nginx
#     image: nginx:stable-alpine
#     ports:
#       - '8080:80'
#     volumes:
#       - .:/var/www/slim_app
#       - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
#     depends_on:
#       - php